config/routes.rb
Rails.application.routes.draw do
  # get "/product/:id", to: "products#edit", as: 'products'
  # put "/product/:id", to: "products#save", as: 'products_update'
  # get "/product", to: "products#new", as: 'product_new'
  # put "/update_is_deleted_product_ajax/:id", to: "products#update_is_deleted_product_use_ajax", as: 'products_update_is_deleted_ajax'
  # post "/product_save_ajax", to: "products#save_ajax", as: 'product_save_ajax'

  get "/", to: "products#index", as: 'index'
  get "/product_detail", to: "products#detail", as: 'product_detail'
  post "/product", to: "products#save", as: 'product_save'
  put "/update_product_ajax", to: "products#update_product_use_ajax", as: 'products_update_ajax'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def detail
    product = Product.find(params[:id])
    respond_to do |format|
      format.json { render json: product }
    end
  end
  def save
    product = Product.new
    product.name = params[:name]
    product.price = params[:price]
    product.description = params[:description]
    product.quantity = params[:quantity]
    product.is_deleted = params[:is_deleted].present? ? params[:is_deleted] : 0
    product.save
  end
  def update_product_use_ajax
    product = Product.find(params[:id])
    product.update(
      name: params[:name],
      price: params[:price],
      quantity: params[:quantity],
      description: params[:description],
      is_deleted: params[:is_deleted]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.haml
= form_with model: @product, url: products_update_path(@product), method: :post do |form|
  = form.label :name
  = form.text_field :name
  %br
  %br
  = form.label :price
  = form.number_field :price
  %br
  %br
  = form.label :quantity
  = form.number_field :quantity
  %br
  %br
  = form.label :description
  = form.text_area :description
  %br
  %br
  = form.radio_button :is_deleted, true , :checked => @product.is_deleted == true
  = form.label :is_deleted, "Disable"
  = form.radio_button :is_deleted, false, :checked => @product.is_deleted == false
  = form.label :is_deleted, "Enable", :value => false
  %br
  = form.submit "Update"

app/views/products/index.html.haml
= javascript_include_tag "application"
= stylesheet_link_tag "application"
%script{src: "https://cdn.jsdelivr.net/npm/sweetalert2@11.1.4/dist/sweetalert2.min.js"}
%link{href: "https://cdn.jsdelivr.net/npm/sweetalert2@11.1.4/dist/sweetalert2.min.css", rel: "stylesheet"}
%script{src: "https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"}
%link{href: "https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css", rel: "stylesheet"}
%script{src: "https://unpkg.com/xlsx/dist/xlsx.full.min.js"}
%script{src: "https://unpkg.com/file-saver/dist/FileSaver.min.js"}
.container
  .row
    .col-md-12
      %h1 Lists all products
      %button#btnExportExcel.btn.btn-info{type: "button"}
        Export to Excel
      -# %button#btnExportPdf.btn.btn-danger{type: "button"}
      -#   Export to PDF
      %p
      %table#myTable.table.table-hover.table-striped.table-bordered
        %thead
          %tr
            %th{scope: "col", :style => "width: 3%"} #ID
            %th{scope: "col", :style => "width: 22%"} Name
            %th{scope: "col", :style => "width: 15%"} Price
            %th{scope: "col", :style => "width: 15%"} Quantity
            %th{scope: "col", :style => "width: 25%"} Description
            %th{scope: "col", :style => "width: 10%"} ON / OFF
            %th{scope: "col", :style => "width: 10%"} Action
        %tbody
          - @products.each_with_index do |prod, index|
            %tr
              %td= index + 1
              %td.view-product{:id => "#{prod.id}"}
                = prod.name
              %td= prod.price
              %td= prod.quantity
              %td= prod.description
              %td.text-center
                %span{:class => (prod.is_deleted == true ? 'off' : 'on')}= (prod.is_deleted == true ? "OFF" : "ON")
              %td{:style => "text-align: center"}
                %input.btn.btn-warning.btn-sm.btn-before-update{:type => "button", :value => "Update", :id => "#{prod.id}"}
.container
  .row
    .text-center
      %input.btn.btn-primary#btnNew{:type => "button", :value => "+"}

app/views/products/new.html.haml
= form_with model: @product, url: product_save_path(@product), method: :post do |form|
  = form.label :name
  = form.text_field :name
  %br
  %br
  = form.label :price
  = form.number_field :price
  %br
  %br
  = form.label :quantity
  = form.number_field :quantity
  %br
  %br
  = form.label :description
  = form.text_area :description
  %br
  %br
  = form.submit "Save"
  = form.button "Back", type: :button, onclick: "window.location='#{index_path}'"